language: node_js
node_js:
  "6"
before_script:
  - rm -rf node_modules
  - npm uninstall -g firebase-tools
  - npm install -g firebase-tools
script:
  - CONTENTFUL_TOKEN=$CONTENTFUL_TOKEN CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID yarn deploy:dev -- --token $FIREBASE_TOKEN
