language: node_js
node_js:
  "6"
before_script:
  - npm install -g firebase-tools
  - npm install
script:
  - CONTENTFUL_TOKEN=$CONTENTFUL_TOKEN CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID yarn deploy:dev -- --token $FIREBASE_TOKEN
